### PR TITLE
Add advanced dev mode

### LINKED ISSUE #88: Create a basic vs advanced install path
We should hide some of the installation paths and user options to avoid confusion about what is needed. This path would automatically install everything and download a single instance of VS Code. We can create an advanced button on the start page that then allows users to select what they want to install. 

This is spawned from feedback in **post6706**.

### PR DESCRIPTION
**Pull request by ThadHouse**
Generally, we don't want users to skip installing VS Code, or to configure any options other then the defaults. Users thinking they have the right stuff is the #1 cause for issues. So add a hidden dev mode, and without it activated disable all configuration options, and the ability to skip VS Code.

Closes #88

### CODE REVIEW

**Comment by calcmogul** [comment]
I noticed if you go all the way to the install button, then backtrack in the installation process to the first page and enable advanced mode, none of the text or checkboxes from advanced mode appear; they only show up if clicking on the logo on the first page is the first thing you do. Not sure if we care about fixing this.

Also, we may want to change the title on this page in non-advanced mode to avoid confusion.
Screenshot_2021-08-17_09-17-11

**Comment by ThadHouse** [comment]
Issue 1 I don't care about fixing. They can restart it if they need to.

The 2nd one yeah I'll make that better.

**Comment by ThadHouse** [comment]
I think we would actually prefer #211 instead. Its a lot more useful and gives teams what they actually want.

**Comment by ThadHouse** [comment]
This has been replaced by just having 2 options, either tools only or everything.

**Pull request closed without merging**
