### PR TITLE
Clear up VS Code installer page text, add file filter

### LINKED ISSUE #83: Installer crashes when something other then a zip is selected for existing vscode download

### PR DESCRIPTION
**Pull request by Starlight220**
Fixes #83.
Accompanies wpilibsuite/frc-docs#919.

### CODE REVIEW

**Comment by ThadHouse** [comment]
That function is used for 2 different file pickers. One needs to be able to handle tar.gz or zip depending on the platform, the other is just zip. So it needs to be a new parameter.

**Comment by Starlight220** [comment]
So I'll work on that; do you know why it isn't finding the `Filter` property? Do I need another import or something?

**Comment by ThadHouse** [comment]
Filter might not exist on the avalonia openfiledialog.

**Comment by Starlight220** [comment]
Fun, this seems to be a known issue: https://github.com/AvaloniaUI/Avalonia/issues/2949

**Review by ThadHouse — APPROVED** [review]

**Pull request merged**
