### PR TITLE
Simplify VS Code download page

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by calcmogul** [comment]
The goal was to include the same information without presenting the user with a wall of text that they won't read.

Here's a screenshot of before (on left) and after (on right).
Screenshot_20211129_004351

**Comment by sciencewhiz** [comment]
Originally the installer provided much less information, very similar to this. Feedback from last years beta was that people didn't know what the buttons did and would choose the wrong options (and didn't read the docs), so the wall of text evolved. I don't like it either, but we did see less user issues afterwards, so I think it's probably better to keep it.

**Comment by ThadHouse** [comment]
Agreed with Joe. As much as I don't like the wall of text, it was requested and does seem to help.

**Comment by calcmogul** [comment]
> we did see less user issues afterwards, so I think it's probably better to keep it.

I disagree. The current installer page's UI design is horrible, and I think we can do better. We should be able to get the main points across without the user's eyes glazing over.

> Feedback from last years beta was that people didn't know what the buttons did and would choose the wrong options

The earliest version of the Avalonia installer I could find (2021.1.1-beta-4) has the verbose version as well. Do you mean the 2020 season Windows installer?

> Originally the installer provided much less information, very similar to this.

The latest push is essentially the same information rephrased to be more digestible. The redundant warning about skipping VS Code was removed because we already pop up a warning when the user clicks that button.

**Comment by calcmogul** [comment]
Screenshot_20211130_144013

**Comment by calcmogul** [comment]
Screenshot_20211130_145503

**Comment by calcmogul** [comment]
Screenshot_20211130_150754

**Comment by calcmogul** [comment]
Screenshot_20211202_192336

**Review by ThadHouse — APPROVED** [review]

**Pull request merged**
