### PR TITLE
Add Python extensions

### PR DESCRIPTION
**Pull request by Gold856**
The main Python extension, Pylance, isort, and autopep8 are included.

### CODE REVIEW

**Comment by auscompgeek** [comment]
🤔 why should we recommend autopep8, when black is more popular?

**Comment by Gold856** [comment]
I didn't actually know that. I just used it because my local setup has autopep8. I can switch it.

**Comment by Gold856** [comment]
Use an open source Python extension where you can download the extension from GitHub.

**Comment by PeterJohnson** [comment]
These artifacts can now be downloaded via Artifactory.  See the changes in #373.

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
