### PR TITLE
Add desktop shortcuts for Glass and SysId

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by PeterJohnson** [comment]
Should we point to the exe’s instead of the vbs?  Perhaps this is a separate issue, but the shortcut icons to other vbs are all the WPILib icon, instead of the actual application icon (at least Glass, OutlineViewer, and SysId have their own icons).  Changing to point to the exe (and not changing the shortcut icon) might be an easy fix at least for those.

**Comment by calcmogul** [comment]
Would that mean we don't need .vbs files for C++ utilities?

**Comment by PeterJohnson** [comment]
What I was saying is that pointing to the .exe should result in it using the correct icon.  I don’t think we need the vbs files for the .exe’s; @ThadHouse does that make sense?

**Comment by sciencewhiz** [comment]
> Perhaps this is a separate issue, but the shortcut icons to other vbs are all the WPILib icon, instead of the actual application icon (at least Glass, OutlineViewer, and SysId have their own icons). 

https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/129

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
