### PR TITLE
Add CLI support

### PR DESCRIPTION
**Pull request by noamzaks**
Could be useful for adding to package managers such as Homebrew, the AUR, chocolatey, etc.
Related to wpilibsuite/homebrew-wpilib#16

### CODE REVIEW

**Comment by noamzaks** [comment]
Console.WriteLine is not working.
Also, installing VSCode and modifying its settings are a tad harder.

Would the approach with a CLI interface be still installing everything on our own or trying to adapt to already installed things like java or vscode? Which could be marked as dependencies in package managers

**Comment by ThadHouse** [comment]
A CLI still should be installing everything. It should just be a flag in the existing installer. 

Console.WriteLine not working is probably something wrong with your system. That not something that would normally break. Have you tried a different system?

**Comment by noamzaks** [comment]
I'll try in a couple of hours

**Comment by noamzaks** [comment]
It was indeed the system (which was Windows 11), it's working for me now (on Linux).
I think only fixing the VSCode installation remains, then this can be ready

**Pull request closed without merging**
