### PR TITLE
Clean up ScriptBase.py, ToolsUpdater.py, and MavenMetaDataFixer.py

### PR DESCRIPTION
**Pull request by calcmogul**
* Simplify tools directory manipulation
* Use snake case for variable names
* Use 4-space indent
* Simplify process waiting logic
* Run black autoformatter

### CODE REVIEW

**Comment by calcmogul** [comment]
These two scripts are identical, so maybe we should deduplicate this somehow?

**Comment by ThadHouse** [comment]
Its doable in gradle to rename when adding it to the zip. I'll look into that.

**Review by ThadHouse — APPROVED** [review]

**Comment by AustinShalit** [comment]
Can we add black as a CI check?

**Comment by calcmogul** [comment]
Yes, but not in this PR. It'll cause unrelated changes in ScriptBaseCpp.py.

**Comment by calcmogul** [comment]
The formatter changes ScriptBaseCpp.py, so we'll need to rebase that branch after this is merged.

**Review by AustinShalit — APPROVED** [review]

**Comment by calcmogul** [comment]
Hold on, I found a bug in the process waiting.

**Comment by calcmogul** [comment]
I think that should match the original script's behavior now.

**Comment by sciencewhiz** [comment]
@AustinShalit @prateekma have either of you tested on mac?

**Comment by prateekma** [comment]
I will test now... one moment

**Comment by prateekma** [comment]
The installation process works and I can open the tools from the VS Code menu.

**Pull request merged**
