### PR TITLE
Only copy permissions for wpilibinstaller executable

### LINKED ISSUE #94: Linux tar.gz has files marked executable that don't need to be
-rwxr--r-- 1 joe joe    1086704 Nov  2 23:03 libHarfBuzzSharp.so
-rwxr--r-- 1 joe joe     920882 Nov  2 23:03 libMonoPosixHelper.so
-rwxr--r-- 1 joe joe    8541744 Nov  2 23:03 libSkiaSharp.so
-rwxr--r-- 1 joe joe    2416513 Nov  2 23:03 System.Reactive.xml

Feedback from post6733

### PR DESCRIPTION
**Pull request by sciencewhiz**
Fixes #94 by not copying permissions for the libraries.

### CODE REVIEW

**Comment by sciencewhiz** [comment]
@prateekma can you verify on macOS?

**Comment by prateekma** [comment]
image

**Comment by sciencewhiz** [comment]
Strange, I expected a problem if the executable was called something other then WPILibInstaller, but I didn't expect this.

**Comment by sciencewhiz** [comment]
@prateekma can you try again?

**Comment by prateekma** [comment]
It works now.

**Review by AustinShalit — APPROVED** [review]

**Pull request merged**
